package gui

const (
	// Create constants for ProcList blocks

	LIBGTK_ADDR				= 0
	LIBGLIB_ADDR				= 100
	LIBGOBJECT_ADDR				= 200

	// GTK dialog flags

	GTK_DIALOG_MODAL			= 1
	GTK_DIALOG_DESTROY_WITH_PARENT		= 2
	GTK_DIALOG_USE_HEADER_BAR		= 4

	// GTK messages

	GTK_MESSAGE_INFO			= 0
	GTK_MESSAGE_WARNING			= 1
	GTK_MESSAGE_QUESTION			= 2
	GTK_MESSAGE_ERROR			= 3
	GTK_MESSAGE_OTHER			= 4

	// GTK buttons

	GTK_BUTTONS_NONE			= 0
	GTK_BUTTONS_OK				= 1
	GTK_BUTTONS_CLOSE			= 2
	GTK_BUTTONS_CANCEL			= 3
	GTK_BUTTONS_YES_NO			= 4
	GTK_BUTTONS_OK_CANCEL			= 5

	// GTK responses

	GTK_RESPONSE_NONE			= 0xffffffff
	GTK_RESPONSE_REJECT			= 0xfffffffe
	GTK_RESPONSE_ACCEPT			= 0xfffffffd
	GTK_RESPONSE_DELETE_EVENT		= 0xfffffffc
	GTK_RESPONSE_OK				= 0xfffffffb
	GTK_RESPONSE_CANCEL			= 0xfffffffa
	GTK_RESPONSE_CLOSE			= 0xfffffff9
	GTK_RESPONSE_YES			= 0xfffffff8
	GTK_RESPONSE_NO				= 0xfffffff7
	GTK_RESPONSE_APPLY			= 0xfffffff6
	GTK_RESPONSE_HELP			= 0xfffffff5

	// GTK file chooser actions

	GTK_FILE_CHOOSER_ACTION_OPEN		= 0
	GTK_FILE_CHOOSER_ACTION_SAVE		= 1
	GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER	= 2
	GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER	= 3

)
